### ISSUE TITLE
Bug: Functions are exported as type-only from commonjs export of `@eslint/config-helpers`

### ISSUE THREAD

**Issue by youngspe** [eslint/rewrite#425]
### Which packages are affected?

- [ ] `@eslint/compat`
- [ ] `@eslint/config-array`
- [x] `@eslint/config-helpers`
- [ ] `@eslint/core`
- [ ] `@eslint/mcp`
- [ ] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`
- [ ] `@eslint/plugin-kit`

### Environment

Node version: v23.10.0
npm version: 10.9.2
ESLint version: 10.2.0
Operating System: Ubuntu 24.04.4 LTS (through WSL)


### What did you do?

My code was importing and calling `defineConfig` from `'eslint/config'`:

```ts
// eslint.config.mjs

import { defineConfig } from 'eslint/config';

defineConfig(/* ... */);
```



### What did you expect to happen?

Ideally, this would type check without any errors.

### What actually happened?

`@typescript/native-preview` gives the following error:

```
eslint.config.cjs:3:1 - error TS1361: 'defineConfig' cannot be used as a value because it was imported using 'import type'.                    
                                                                                                                                               
3 defineConfig(/* ... */);                                                                                                                              
  ~~~~~~~~~~~~                                                                                                                                 
                                                                                                                                               
  node_modules/@eslint/config-helpers/dist/cjs/index.d.cts:1:18 - 'defineConfig' was imported here.                                            
    1 import type * as types from "../esm/index.js" with { "resolution-mode": "import" };        
```

### Link to Minimal Reproducible Example

https://github.com/youngspe/eslint-types-example

### Participation

- [x] I am willing to submit a pull request for this issue.

### AI acknowledgment

- [x] I did not use AI to generate this issue report.
- [ ] (If the above is not checked) I have reviewed the AI-generated content before submitting.

### Additional comments

Looks like this was introduced by #416 

`@eslint/config-helpers/dist/cjs/index.d.cjs` looks like this as of  `@eslint/config-helpers@0.5.2`:

```ts
import type * as types from "../esm/index.js" with { "resolution-mode": "import" };
export = types;
```

Since the functions `defineConfig` and `globalIgnores` are imported through `import types` before being re-exported, they're techincally type-only exports.

This causes build errors with `@typescript/native-preview@^7.0.0-dev.20260404.1` when calling those functions, either directly through `'@eslint/config-helpers'` from a commonjs module or through `'eslint/config'` from any module. Curiously, `typescript@6.0.2` is not reporting errors, though as far as I can tell it _should_ because it's still a re-export of a type-only import.

This likely applies to other packages changed by #416 but I haven't checked that.

Feel free to close if this is a won't-fix because it only fails on a pre-production TypeScript compiler version.

**Comment by lumirlumir** [comment]
Hi @youngspe — thanks for the report. I can reproduce this with the TypeScript v7 native preview (`@typescript/native-preview@^7.0.0-dev.20260404.1`), and I've confirmed the error does not occur with TypeScript v6 (`typescript@6.0.2`).

I believe this issue is caused by TypeScript v7 enforcing stricter type tracking for re-exports than v6.

I'd be in favor of fixing this if a straightforward solution exists, since TypeScript v7 usage will likely increase over time. One concern, though, is that TypeScript v7 is still in development and, as mentioned, its behavior could change in the future.

What should our policy be regarding TypeScript v7 compatibility? Any thoughts, @eslint/eslint-team?

**Comment by DMartens** [comment]
I think we should start checking for TypeScript v7 support as soon as the first release candidate releases, which according to their [blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-6-0/#preparing-for-typescript-7.0) is only a few months away.

**Comment by youngspe** [comment]
My intuition is that we can just remove the `type` modifier from the `import type` statements in the generated `d.cts` files. Since they just re-export the ES module declaration, anything that's safe to import by value with `import` should be safe to import with `require()`. But there could definitely be something I'm missing.

**Comment by fasttime** [comment]
Thanks for the report, @youngspe. I am able to reproduce the problem with the TypeScript 7 preview. Not sure if that's a bug or if they changed the behavior. Type resolution should be the same as in TS 6.0 according to [their documentation](https://github.com/microsoft/typescript-go?tab=readme-ov-file#what-works-so-far).

> My intuition is that we can just remove the `type` modifier from the `import type` statements in the generated `d.cts` files.

The `.d.cts` file for `@eslint/config-helpers` looks currently like this:

```ts
import type * as types from "../esm/index.js" with { "resolution-mode": "import" };
export = types;
```

Here, `import type` is required because of the `{ "resolution-mode": "import" }` attribute. If you replace it with a plain `import`, the compiler reports an error:

> error TS2856: Import attributes are not allowed on statements that compile to CommonJS 'require' calls.

> Since they just re-export the ES module declaration, anything that's safe to import by value with `import` should be safe to import with `require()`. But there could definitely be something I'm missing.

The ability to require ESM modules was only introduced in TS 5.8 ([release announcement](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-8.html#support-for-require-of-ecmascript-modules-in---module-nodenext)). Even a plain import like `import * as types from "../esm/index.js";` doesn't work in previous TypeScript versions.

**Comment by youngspe** [comment]
You're right, I didn't realize that was introduced so recently. If there's no way to make this work for both <5.8 and >=7.0 maybe that is a bug in `tsgo`. I'll see if I can find out if that's an intentional change or not.

**Comment by youngspe** [comment]
Apparently, somebody filed an issue for this yesterday. It looks like this is not a compiler bug and will occur in the TypeScript 7.0 release: https://github.com/microsoft/typescript-go/issues/3347#issuecomment-4194141803 .

**Comment by fasttime** [comment]
> Apparently, somebody filed an issue for this yesterday. It looks like this is not a compiler bug and will occur in the TypeScript 7.0 release: [microsoft/typescript-go#3347 (comment)](https://github.com/microsoft/typescript-go/issues/3347#issuecomment-4194141803) .

Well, at least that helped someone realize that there's a bug in TypeScript <= 6.0. Given the current status, I see several options to proceed here:

1. Revert the changes in #416. That means we won't be able to resume work on eslint/eslint#19843 for now. Not ideal, but that's how it has been so far. This is the safest option.
2. Generate CommonJS type declarations and re-export them in ESM as suggested in the typescript-go issue. This has always been an option (we already do it in `eslint-scope`), but it's somewhat problematic in this repo. We'd also need to confirm that the JSR package still works since it expects ESM modules only.
3. Document that TypeScript 7 isn't currently supported. This probably makes the most sense since it seems we can't count on backward compatibility and there may be other disruptions up to the final TS 7 release. We could revisit once support for TS < 5.8 is dropped.

**Comment by mnaoumov** [comment]
This also affects `@eslint/compat` — its `dist/cjs/index.d.cts` uses the same `import type * as types` + `export = types` pattern introduced by #416.                                                                                                                                                                   

In our case, `eslint-plugin-import-x`'s `import-x/named` rule resolves `@eslint/compat` to the CJS `.d.cts` (because `require` appears before `import` in the package's `exports` field), and since `export = types` doesn't expose individual named exports to static analysis, it reports `includeIgnoreFile` as not found — even though it exists at runtime and in the ESM `.d.ts`.

This is a slightly different manifestation than the TS7 issue (it's a linter false positive rather than a type error), but same root cause.

**Comment by mdjermanovic** [comment]
If I understand correctly that we're currently relying on a behavior that is considered a bug in TypeScript, and it also breaks some other static analysis as mentioned by @mnaoumov, then I think the best course of action at the moment is to revert changes (1.) and release patches. Then, we could later consider another solution (e.g, 2.) and have time to test it with different scenarios.

**Comment by silverwind** [comment]
https://www.npmjs.com/package/@typescript/native-preview has almost 4 million weekly downloads as of today. I think not supporting `tsgo` would be a bad choice, it's gaining massive adoption and I think you should test against it.

**Comment by nzakas** [comment]
I agree with @mdjermanovic's analysis. Marking as accepted.

**Comment by mnaoumov** [comment]
**UPD**: It is partially repeating the original message. I apologize for that.

Similar problem with

```ts
import { defineConfig } from 'eslint/config';
```

error

```
'defineConfig' resolves to a type-only declaration and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled. ts(1485)
```

and then

```
'defineConfig' cannot be used as a value because it was imported using 'import type'. ts(1361)
```

The workaround is

```ts
import { defineConfig } from '@eslint/config-helpers';
```

which however has the same problem with [import-x/named](https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/named.md)

**Comment by mnaoumov** [comment]
I would suggest the following fix I use in one of my projects

I generate `types.d.cts` and `types.d.mts`

`types.d.cts` has actual content

`types.d.mts` looks like

```ts
export type * from '../cjs/types.d.cts' with { 'resolution-mode': 'import' };
```
